name: texastodo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^3.1.17
  flutter_screenutil: ^5.9.3
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  get: ^4.7.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
