// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCobKwrRLH3mY6HcaT69j1uv4hxgVrZeh4',
    appId: '1:52790263940:web:a2960fe20e3261f52002d1',
    messagingSenderId: '52790263940',
    projectId: 'todos-6a5cb',
    authDomain: 'todos-6a5cb.firebaseapp.com',
    storageBucket: 'todos-6a5cb.firebasestorage.app',
    measurementId: 'G-GE7TZE04P7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuaCJ4qNKgUqXxfyDFpNF_3PueK_e_AFw',
    appId: '1:52790263940:android:a3c97c38b4c643a12002d1',
    messagingSenderId: '52790263940',
    projectId: 'todos-6a5cb',
    storageBucket: 'todos-6a5cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr5O3o0391SsUNGHCwp5yszXhiI9iSF5k',
    appId: '1:52790263940:ios:6da1bc3464928f562002d1',
    messagingSenderId: '52790263940',
    projectId: 'todos-6a5cb',
    storageBucket: 'todos-6a5cb.firebasestorage.app',
    iosBundleId: 'com.example.texastodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr5O3o0391SsUNGHCwp5yszXhiI9iSF5k',
    appId: '1:52790263940:ios:6da1bc3464928f562002d1',
    messagingSenderId: '52790263940',
    projectId: 'todos-6a5cb',
    storageBucket: 'todos-6a5cb.firebasestorage.app',
    iosBundleId: 'com.example.texastodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCobKwrRLH3mY6HcaT69j1uv4hxgVrZeh4',
    appId: '1:52790263940:web:5d07c363ed2ebcee2002d1',
    messagingSenderId: '52790263940',
    projectId: 'todos-6a5cb',
    authDomain: 'todos-6a5cb.firebaseapp.com',
    storageBucket: 'todos-6a5cb.firebasestorage.app',
    measurementId: 'G-QVJ1V7C7XW',
  );
}
